[Comic Info]
Comic name = Your Comic Name
Author = Your Name Here
Description = A short description of your comic.

[Comic Settings]
Engine version = 1.1
Date format = %B %d, %Y
# Change this to your local timezone.
Timezone = US/Pacific

[Pages]
index = Welcome to comic_git!
latest =
archive = Archive
tagged = Tagged Posts
infinite_scroll = Infinite Scroll
404 = Page Not Found

[Links Bar]
Home = /
Archive = /archive/
Infinite Scroll = /infinite_scroll/
Patreon = ^https://www.youtube.com/watch?v=dQw4w9WgXcQ

[Archive]
# To use thumbnails in your archives, you must also set "Create thumbnails" to "True"
# in the [Image Reprocessing] section, or manually create your own
Use thumbnails = True

[Image Reprocessing]
Create thumbnails = True

[RSS Feed]
Build RSS feed = True

[Transcripts]
Enable transcripts = True
